name: SSR Scraper
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ssr-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - name: Fetch and Check Nodes
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Encode and Push
        run: |
          sort -o nodes.txt nodes.txt
          cat nodes.txt | base64 > subscribe.txt
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add nodes.txt subscribe.txt stats.json
          git commit -m "Updated: $(date -u +"%D %T %Z")" --allow-empty
          git push origin HEAD:master
